name: 3DKreatorUSA
favicon: null
layout_spectrum: 0.25037
typography_spectrum: 0.4992
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 3DKreatorUSA
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#141318'
    - '#017dc5'
    - '#797880'
    - '#82ceea'
  brandStrength: 0.875
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
