title: 3DKreatorUSA
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6875
  brandStrength: 0.625
  rhythmicContrast: 0.75
  brandColors:
    - '#ffffff'
    - '#141318'
    - '#017dc5'
    - '#797880'
    - '#82ceea'
  lightness: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: 3DKreatorUSA
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4992
layout_spectrum: 0
