name: 3DKreatorUSA
favicon: null
layout_spectrum: 0.25301
typography_spectrum: 0.22889
title: 3DKreator USA
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#141318'
    - '#017dc5'
    - '#797880'
    - '#a8b7d6'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
