name: 3DKreatorUSA
favicon: null
layout_spectrum: 0.49899
typography_spectrum: 0.1072047718334943
title: 3DKreator USA
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.625
  lightness: 0.7726233322173357
  saturation: 0.5
  rhythmicContrast: 0.8631649070885032
purpose: []
